networks:
  hdox:

volumes:
  hdox_pg:
  pgadmin:

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    networks:
      - hdox
    volumes:
      - hdox_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
  web:
    image: hdox
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PORT: $DB_PORT
      DB_PASS: $DB_PASS
      DB_HOST: $DB_HOST
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - hdox
    volumes:
      - ./out/:/app/out/
    depends_on:
      pg:
        condition: service_healthy
  pg_admin:
    image: dpage/pgadmin4
    networks:
      - hdox
    environment:
      PGADMIN_DEFAULT_EMAIL: adm@adm.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 127.0.0.1:80:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      pg:
        condition: service_healthy
